#- name: Configure EC2 for Spring Boot
#  hosts: all
#  become: true
#  tasks:
#    - name: Install Docker
#      ansible.builtin.yum:
#        name: docker
#        state: present
#      notify:
#        - Start Docker
#
#    - name: Add ec2-user to Docker group
#      ansible.builtin.user:
#        name: ec2-user
#        groups: docker
#        append: yes
#
#    - name: Install Java (for Jenkins)
#      ansible.builtin.yum:
#        name: java-11-openjdk-devel
#        state: present
#
#  handlers:
#    - name: Start Docker
#      ansible.builtin.service:
#        name: docker
#        state: started
#        enabled: yes
#
#- name: Check if port 8081 is free
#  ansible.builtin.command: netstat -tuln | grep 8081
#  register: port_check
#  failed_when: port_check.rc == 0  # Fail if port is occupied
#  changed_when: false